### ISSUE TITLE
Getting XHR error (404 Not Found) loading http://localhost:3000/amp-dash  

### ISSUE THREAD

**Issue by mailmrmanoj** [nisheed2440/ng2-amp-dash#2]
Hi,
I'm trying to import amp-dash module in my app.module.ts file.When I inject it in my `app.module.ts` file  like the one below
 
```
@NgModule({
    declarations: [AppComponent, HeaderAppComponent, GitUsers, HttpComponent, FooterComponent],
    imports: [BrowserModule, HttpModule, AmpDashModule],
    providers: [],
    bootstrap: [AppComponent, HeaderAppComponent, GitUsers, HttpComponent, FooterComponent]
})
```
getting an error  in console and nothing loads in browser. Please let me know where I'm doing wrong.Code link [https://github.com/mailmrmanoj/angular-graphql-integration](https://github.com/mailmrmanoj/angular-graphql-integration)
![amp-dash-error](https://cloud.githubusercontent.com/assets/7077567/25514441/b9816a32-2bfa-11e7-854e-fc929150247a.JPG)

**Comment by nisheed2440** [comment]
@mailmrmanoj, are you using ng-cli or SystemJS with custom config.

**Comment by mailmrmanoj** [comment]
System.config.js
Not using ng-cli

**Comment by nisheed2440** [comment]
@mailmrmanoj, currently the amp-dash version only works projects built on ng-cli. But based on your input , i am working on updating it to also work with system JS

**Comment by mailmrmanoj** [comment]
ok Thanks for the info @nisheed2440

**Comment by nisheed2440** [comment]
1. run `npm install -save amp-dash@latest` 

2. **Make the following changes in your systemjs.config.js file**

```javascript
 var map = {
        'app': 'dist', // 'dist',
        '@angular': 'node_modules/@angular',
        'rxjs': 'node_modules/rxjs',
//add the below line to let system know where to resolve amp-dash from
        'amp-dash': 'node_modules/amp-dash'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': {
            main: 'main.js',
            defaultExtension: 'js'
        },
        'rxjs': {
            defaultExtension: 'js'
        },
//add the below config to let system know which is the main file to use
        'amp-dash': {
            main: 'lib/index.umd.js',
            defaultExtension: 'js'
        }
    };
```

3. Now you can add the module dependency in you app.module.ts file as below
```typescript
/** **/
import {AmpDashModule} from 'amp-dash';

@NgModule({
    imports: [BrowserModule,HttpModule,AmpDashModule ]
/** **/
})
```
Amp dash component should now work. Tested it locally by cloning your repo

**Comment by nisheed2440** [comment]
@mailmrmanoj Closing issue as it has been tested locally

**Comment by mailmrmanoj** [comment]
@nisheed2440 thanks for an update. Great help :-)

On 1 May 2017 1:38 p.m., "nisheed2440" <notifications@github.com> wrote:

*Make the following changes in your systemjs.config.js file*
//////// var map = { 'app': 'dist', // 'dist', '@angular':
'node_modules/@angular', 'rxjs': 'node_modules/rxjs', 'amp-dash':
'node_modules/amp-dash' }; // packages tells the System loader how to load
when no filename and/or no extension var packages = { 'app': { main:
'main.js', defaultExtension: 'js' }, 'rxjs': { defaultExtension: 'js' },
'amp-dash': { main: 'lib/index.umd.js', defaultExtension: 'js' } }; //////

Now you can add the module dependency in you app.module.ts file as below
`
////
import {AmpDashModule} from 'amp-dash';

@NgModule <https://github.com/NgModule>({
imports: [BrowserModule,HttpModule,AmpDashModule ]
///
`
Amp dash component should now work. Tested it locally by cloning your repo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nisheed2440/ng2-amp-dash/issues/2#issuecomment-298302581>,
or mute the thread
